# Generated by Django 5.0.6 on 2026-09-18 18:38

import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('policy', 'Policy'), ('faq', 'FAQ'), ('delivery', 'Delivery'), ('general', 'General')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('product', 'Product'), ('business_info', 'Business Info')], max_length=20)),
                ('source_id', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('embedding', pgvector.django.VectorField(dimensions=768)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='chatbot_kno_source__49681f_idx')],
            },
        ),
    ]
